# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc68ad1799257404562a7477b57d6c02ea9d781f88c00da06937ffca901968a515b13f6639e5ee5790675ca13e69360fdaf607dcd61abecf1f7b1de9840346d

test:
  secret_key_base: f98e43cc2cd5ad9bf5d0acb0fa73cbfc8dff4cbc19ae21bcc17b26ed9b4854a136d6fb2bf269fbff8afa3b19049ee7b48aba86c7e79d9afda661947a26400086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
